name: cbl_flutter_example
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  cbl: ^3.0.0
  cbl_flutter: ^3.0.0
  cbl_flutter_ce: ^3.0.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner:

flutter:
  uses-material-design: true
